project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "EDS 222"
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/14WaSESgCsRoDvpfr6UMWIGT9tYXEKnlhup5KK9sarWM/edit?usp=sharing
        target: _blank
      - text: daily materials
        menu:
          - text: week 1 (10/1)
            href: course-materials/week1.qmd
          - text: week 2 (10/8)
            href: course-materials/week2.qmd
          - text: week 3 (10/15)
            href: course-materials/week3.qmd
          - text: week 4 (10/22)
            href: course-materials/week4.qmd
          - text: week 5 (10/29)
            href: course-materials/week5.qmd
          - text: week 6 (11/5)
            href: course-materials/week6.qmd
          - text: week 7 (11/12)
            href: course-materials/week7.qmd
          - text: week 8 (11/19)
            href: course-materials/week8.qmd
          - text: week 9 (11/26)
            href: course-materials/week9.qmd
          - text: week 10 (12/3)
            href: course-materials/week10.qmd
      - icon: github
        href: https://github.com/eds-222-statistics
        target: _blank
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/flukeandfeather/eds-222-stats.github.io), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html) and [Quarto](https://quarto.org/)
    left: |
      <img src="images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>


format:
  html:
    theme: meds-website-styles.scss
    toc: true
    title-block-banner: true
    page-layout: full

editor: source



